name: ci

on:
  push:

env:
  PAPER_VERSION: "1.18.2"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build
        run: |
          docker buildx build \
          --build-arg version=$PAPER_VERSION
          --push \
          --platform linux/arm64/v8 \
          --tag nicoenking/minecraft-papermc-server:$PAPER_VERSION .